name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ruff Linter
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github
          src: "./src"
      - name: Run Ruff Formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff
          src: "./src"